version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: quizappcontainer
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      -
  quizapp:
    image: quizapp
    container_name: quizapp
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/

volumes:
  mongo-data:



